### ISSUE TITLE
Feature Request: Add Support for IR Timecode Reset

### ISSUE THREAD

**Issue by sturmen** [frank26080115/alpha-fairy#13]
There's one specific Sony IR remote control that includes a "timecode reset" button, which you can use in a multi-cam setup to simultaneously reset all of the Sony cameras to the same timecode, synchronizing them. [Here's a video](https://youtu.be/eH53yZi3vhc). I believe this would be a great addition to Alpha Fairy, and would also help people get this functionality long after Sony stops manufacturing RMT-845 remotes!

**Comment by frank26080115** [comment]
I can try

If you can tell me the 7 bit command that's being sent, it would help a lot

The infrared LED on the M5StickC isn't as powerful as a remote with a large LED. Please keep that in mind.

**Comment by frank26080115** [comment]
I tried all 127 possible commands, none of them reset the time code, tested on my A1 and A6600

**Comment by sturmen** [comment]
I have the remote around here somewhere; how would I be able to capture the IR command?

**Comment by frank26080115** [comment]
I actually did some looking around multiple IR code databases and didn't find anything for this remote, I didn't want this information to be lost forever so I actually obtained one myself and already finished reverse engineering it.

The IR codes I have put inside https://github.com/frank26080115/alpha-fairy/blob/main/arduino_workspace/libraries/SonyCameraInfraredRemote/SonyCameraInfraredRemote.h

For anybody visiting this page via search engine, the code is `#define IR_CMD_RMT845_TCRESET     0x3D7D   // 20 bits, repeat 5 times`

Version 1.0.10 of Alpha-Fairy has a new menu item added to send the timecode reset command. Please update both the firmware and the image file data.

**Comment by frank26080115** [comment]
documentation and instructions have been updated to include this feature

please test and report back if it works with your camera, then I'll close it

I tested on my A1 and it worked

**Comment by sturmen** [comment]
This is fantastic, thank you so much! My M5StickC PLUS is still in the mail; can't wait to try it out!
