### ISSUE TITLE
[Feature Request] Avoid showing up changed files in Source Control if using PlatformIO

### ISSUE THREAD

**Issue by elral** [frank26080115/alpha-fairy#29]
Great to see that compiling with PlatformIO is supported!

**Is your feature request related to a problem? Please describe.**
After cloning the repo and compiling with PlatformIO, a lot of changed files appear in the Source Control.

**Describe the solution you'd like**
Add to the end of file `.gitignore`:

`#PlatformIO`
`.pio`

to avoid showing up multiple changed files in the source control.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by frank26080115** [comment]
how in the hell did you open this ticket literally a few hours after I accepted that pull request?

anyways... I did it, https://github.com/frank26080115/alpha-fairy/commit/8c2cacb7153c6fa52843a73e0b2b5744341d1a94 and also updated instructions for PlatformIO with screenshots

**Comment by elral** [comment]
I just opened your repo yesterday to read again the documentation as I had some problems to control my Alpha IV.  
 It was pure coincidence. And as I am using PlatformIO for other projects I gave it directly a try (and learned that .ino files can (now?) directly used).

Sorry if I was too fast...
